### ISSUE TITLE
Gradle Build fails

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [SegwayRoboticsSamples/AIBoxSample#1]
I'm trying to build this project using the following configuration:
```
sdk.dir=/home/caio/Android/Sdk
ndk.dir=/home/caio/Android/Sdk/ndk/16.1.4479499
cmake.dir=/home/caio/Android/Sdk/cmake/3.6.4111459
```
(That's the only change that I did it)

But I'm getting the errors:
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
```
```
cvc-complex-type.2.4.a: Invalid content was found starting with element 'extension-level'. One of '{layoutlib}' is expected.
```
```
cvc-complex-type.2.4.d: Invalid content was found starting with element 'base-extension'. No child element is expected at this point.
```

Do you know what might be the issue?

Here's the full log:
[error_gradle_build.txt](https://github.com/SegwayRoboticsSamples/AIBoxSample/files/11203186/error_gradle_build.txt)

I'm using Android Studio version:
```
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.14.0-1059-oem
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    IdeaVIM (1.10.3)
    com.thoughtworks.gauge (221.6008.13)

Current Desktop: ubuntu:GNOME
```

**Comment by LixinLu42** [comment]
hi,@caiotoledo-lunasystems
We recommend using Android Studio version 4.0.2 (refer to readme)
if using Android Studio Electric Eel | 2022.1.1 Patch 2 version, you can make the following modifications：
1.in file local.properties:(using cmake version 3.10.2):
`
sdk.dir=/Library/Android/sdk
ndk.dir=/Library/Android/sdk/ndk/16.1.4479499
cmake.dir=/Library/Android/sdk/cmake/3.10.2.4988404
`

2.in file build.gradle:
`dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
}`

3.in file gradle/wrapper/gradle-wrapper.properties：
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
`
Then recompile it.

**Comment by caiotoledo-lunasystems** [comment]
Hello @LixinLu42,

Thanks for the help it worked!

Here are my changes:

- `local.properties`:
```
sdk.dir=/home/caio/Android/Sdk
cmake.dir=/home/caio/Android/Sdk/cmake/3.10.2.4988404
```

- `build.gradle`:
```
dependencies { classpath 'com.android.tools.build:gradle:4.2.2' }
```

- `gradle/wrapper/gradle-wrapper.properties`:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip
```

- `sample_aibox/build.gradle`:
```
jniLibs.srcDirs = ['src/main/libs', 'src/main/cpp/lib']
```
I had to remove the `"src/main/cpp/dependency/3rdparty_android/tensorflow_lite_gpu_delegate/lib"` because the building process said that the cmake was already adding the tensorflow libraries.
